name: Monitor Corrupción España (PLACSP)

on:
  schedule:
    # 07:00 UTC equivale a:
    # - 04:00 AM en Argentina (UTC-3)
    # - 08:00 AM en España (UTC+1)
    - cron: '0 7 * * *'
  workflow_dispatch: # Permite ejecución manual con el botón "Run workflow"

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install pandas requests lxml

      - name: Ejecutar Robot España
        run: python diario_es.py

      - name: Guardar Reporte (Commit & Push)
        run: |
          git config --global user.name 'Robot Monitor España'
          git config --global user.email 'robot-spain@noreply.github.com'
          
          # 'git add .' evita errores si la carpeta data está vacía
          git add .
          
          # Solo sube cambios si hay archivos nuevos para evitar marcar error
          git diff --staged --quiet || (git commit -m "Reporte Automático: $(date +'%Y-%m-%d')" && git push)
