name: Monitor Diario BORA

on:
  schedule:
    # Cron job para las 10:00 UTC (Son las 07:00 AM en Argentina)
    - cron: '0 10 * * *'
  workflow_dispatch: # Permite que lo ejecutes manualmente con un botón si quieres probar

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install pandas requests beautifulsoup4 openpyxl

      - name: Ejecutar Robot
        run: python diario.py

      - name: Guardar Reporte (Commit & Push)
        # Esto sube el Excel nuevo a tu repositorio automáticamente
        run: |
          git config --global user.name 'Robot Monitor'
          git config --global user.email 'robot@noreply.github.com'
          git add data/*.xlsx
          git commit -m "Reporte Automático: $(date +'%Y-%m-%d')" || exit 0
          git push